### PR TITLE
EdkRepo: Making messaging framework consistent

### PR DESCRIPTION
**Pull request by kevinsun49**
Refactoring to avoid known colorama behavior that would cause exponential amount of recursive calls. Includes establishing consistent standardized messaging framework in all commands for future use.

Signed-off-by: Kevin Sun <kevinsun@intel.com>

### CODE REVIEW

**Comment by kevinsun49** [comment]
Colorama issue and discussion found at  https://github.com/tartley/colorama/issues/140

**Comment by kevinsun49** [comment]
> I recommend updating the copyright date for all of these files

Should be fixed now. Thank you for the heads up.

**Review by ashedesimone — CHANGES_REQUESTED** [review]
All commands do not inherit the color arg by default. For those commands which don't we should either add that argument or remove the call to init color console. 
For the commands that do inherit the color argument and more specifically the manifest command this change works well.

**Review by ashedesimone — CHANGES_REQUESTED** [review]
Each commit message needs to have consistent formatting. Title should be EdkRepo: x followed by a description and signed off by. 

You have several changed files that only change the copyright date or whitespace. These changes are not within the scope of this change and should be removed. 

I suggest breaking this change into commits as follows:
commit 1: add the color argument to the composite command and remove it from any command that explicitly adds it
commit 2: Fix the bug. ex. Add the call to init_color_console() in the composite command and remove from any command that explicitly calls it.
commit 3: fix any other bugs you have found (it looks like in log_command.py)

**Comment by kevinsun49** [comment]
Closing this PR and opening #56, which is equivalent but properly encapsulates all changes stemming from this conversation.

**Pull request closed without merging**
